--CREATE TABLE Brew (Id INTEGER PRIMARY KEY AUTOINCREMENT, BrewName CHAR (255) NOT NULL, BrewType CHAR (255), BrewHops CHAR (255), BrewMalt CHAR (255), BrewYeast CHAR (255), BrewOg NUMERIC DEFAULT (0), BrewFg NUMERIC DEFAULT (0), BrewEbc NUMERIC DEFAULT (0), BrewIbu NUMERIC DEFAULT (0), Photo BOOLEAN)

--CREATE TABLE BrewDirections (Id INTEGER PRIMARY KEY AUTOINCREMENT, BrewId INTEGER NOT NULL, SortOrder INTEGER, Direction CHAR (255))

CREATE TABLE [Logs] ( [Id] INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, [DateTime] TIME NOT NULL, [Message] TEXT NULL )

CREATE TABLE [Schedule] ( [Id] INTEGER PRIMARY KEY AUTOINCREMENT NULL, [BrewId] INTEGER NOT NULL, [StartDate] DATETIME NULL, [ItemName] CHAR (255) NULL )

CREATE TABLE SensorData (Id INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE, SensorId INTEGER NOT NULL, DateTime DATETIME NOT NULL, SensorValue NUMERIC)

CREATE TABLE Sensors (Id INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE, SensorId CHAR (32) NOT NULL, SensorName CHAR (32) NOT NULL, SensorType CHAR (32) NOT NULL, MinValue NUMERIC, MaxValue NUMERIC)

CREATE TABLE "Settings" ( `Id` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE, `Title` TEXT, `Description` TEXT, `Active` NUMERIC NOT NULL DEFAULT 0 )

CREATE TABLE Widgets (Id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, Widget CHAR (50) NOT NULL, Title CHAR (50), Size CHAR (50) NOT NULL, Theme CHAR (50) NOT NULL, Multipage BOOLEAN, SortOrder INT NOT NULL, Active BOOLEAN, Persistent BOOLEAN)