api:
  basepath: http://127.0.0.1:5000/api/v1

camera:
  mode: file #ftp | file | live
  path: /data/websites/greenhouse.local/www/snapshots/snapshot.jpg
  username: username
  password: password

enviroment:
  debug: false